<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-06-10 18:23:45",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "bd12a198b2e1c3b80b8565aff18c9340",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-06-10 18:22:45",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "0472a1294712e3c59c43387c96c14402",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-06-10 18:21:45",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "757c64fe90b77e80ca7a6f0f5f6d5f81",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2020-06-10 18:20:45",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "0e5d87896010ce0c1ae5b5cce8c42190",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}